### PR TITLE
Upgrade hup-action-utils to 3.0.0

### PR DESCRIPTION
**Pull request by imrehg**
Depends-on: https://github.com/balena-io/resin-proxy/pull/389
Change-type: minor
Signed-off-by: Gergely Imreh <gergely@balena.io>

---
##### Contributor checklist

- [ ] Includes tests
- [ ] Includes typings
- [ ] Includes updated documentation
- [ ] Includes updated build output

### CODE REVIEW

**Comment by imrehg** [comment]
@thgreasi tested it with the UI + new proxy, and seems to work like a charm at least on that end.

**Comment by thgreasi** [comment]
Great @imrehg :+1:

**Comment by imrehg** [comment]
@balena-ci retest please

**Comment by imrehg** [comment]
@thgreasi seems like appveyor is acting up again?

**Comment by thgreasi** [comment]
Oh wait, that's just an API hickup @imrehg  (I think).
Just restarted the tests, let's see.

**Pull request merged**
