### PR TITLE
Update balena-request to v11.4.2

### PR DESCRIPTION
**Pull request by klutchell**
Update balena-request from 11.4.1 to 11.4.2

Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

---
##### Contributor checklist

- [ ] Includes tests
- [ ] Includes typings
- [ ] Includes updated documentation
- [ ] Includes updated build output

### CODE REVIEW

**Comment by klutchell** [comment]
@balena-ci I self-certify!

**Comment by klutchell** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
@klutchell I restarted the tests from appveyor (balena-ci retest doesn't do that).
```
FAILED TESTS:
  Logs
    given a device
      balena.logs.history()
        ✖ should successfully load historical logs
          HeadlessChrome 79.0.3945 (Windows 8.1.0.0)
        O: Request error: The API cannot handle your request right now
            at Object.<anonymous> (es2015/balena-browser.min.js:1:121658)
            at Generator.next (<anonymous>)
            at n (es2015/balena-browser.min.js:1:503680)
```
Looks like it's related to what was reported at:
See: https://www.flowdock.com/app/rulemotion/resin-devops/threads/vRYzOsq21lcYUHQFIX42_x1DxQc

**Comment by klutchell** [comment]
> Looks like it's related to what was reported at

@thgreasi thanks, that's what I suspected as well with the API timeouts

**Comment by LinusU** [comment]
Since you don't have a package lock file I think that you can just rerun the jobs and they should pick up the new version 🚀

**Pull request merged**
