### PR TITLE
Add name and description field to generateDeviceKey for device.

### PR DESCRIPTION
**Pull request by nitishagar**
Change-Type: minor
Signed-off-by: Nitish Agarwal <1592163+nitishagar@users.noreply.github.com>

Depends-on: https://github.com/balena-io/open-balena-api/pull/948

### CODE REVIEW

**Review by thgreasi — APPROVED** [review]
LGTM But remember to also run `npm run build` to generate the docs.

**Comment by nitishagar** [comment]
@balena-ci retest

**Comment by nitishagar** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
@nitishagar did you check why appveyor fails?
```
FAILED TESTS:
  Device Model
    given an application
      given a single offline device
        [contained scenario]
          balena.models.device.generateDeviceKey()
            ✖ should be able to generate a device key with name and description
              HeadlessChrome 79.0.3945 (Windows 8.1.0.0)
            AssertionError: expected { id: 5882526, …(5) } to have property 'name' of 'device_key', but got null
                at Context.<anonymous> (webpack:///tests/integration/models/device.spec.js:1001:35 <- 
```
Does it pass locally for you?

**Comment by nitishagar** [comment]
@thgreasi Yes I checked the appveyor logs and this passes locally (using stage env). But this should pass in prod now as well.

**Pull request merged**
