### PR TITLE
Fix the billing.updateBillingInfo tests

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: patch
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

---
##### Contributor checklist

- [ ] Includes tests
- [ ] Includes typings
- [ ] Includes updated documentation
- [ ] Includes updated build output

### CODE REVIEW

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
Closing in favor of https://github.com/balena-io/balena-sdk/pull/708, since the accidental `=` in the branch name is blocking balena-ci.

**Pull request closed without merging**
